# Generated by Django 5.1.2 on 2024-11-03 12:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('row_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('date_of_birth', models.DateField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='valix.uploadedfile')),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
