# Generated by Django 5.1.2 on 2024-11-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
